### ISSUE TITLE
Found a certificate rather than a key in the PEM for the private key

### ISSUE THREAD

**Issue by garvi-x** [brocaar/loraserver-certificates#4]
Hi!!

I'm including the certificates in the lora-geo-server.toml as explained in this repository. However, the container exits the execution with a fatal error.

The last lines in the container log are:

```
time="2018-10-08T14:36:44Z" level=info msg="starting api server" bind="geoserver:8005" ca_cert=/etc/certs/ca/ca.pem tls_cert=/etc/certs/lora-geo-server/api/server/lora-geo-server-api-server.pem tls_key=/etc/certs/lora-geo-server/api/server/lora-geo-server-api-server-key.pem
time="2018-10-08T14:36:44Z" level=fatal msg="load key-pair error: tls: found a certificate rather than a key in the PEM for the private key" cert=/etc/certs/ca/ca.pem key=/etc/certs/lora-geo-server/api/server/lora-geo-server-api-server.pem
```
Could the certificates not have been created correctly?

I'm waiting for the answers. Thanks! :+1:

**Comment by brocaar** [comment]
Thanks for reporting 👍 The issue has been fixed.

**Comment by garvi-x** [comment]
Hello @brocaar !!

I don't understand it, the geoserver continues to fail for the same problem with tls certificates. I seen your fix in the code to lora-geo-server, but my problem continue. It's strange :/

**Comment by brocaar** [comment]
Sorry, this hasn't been released yet. I'm releasing this right now :)

**Comment by garvi-x** [comment]
No problem! Thanks! :))

**Comment by brocaar** [comment]
It has been released. You should be able to upgrade to LoRa Geo Server v2.0.1 :)
